### PR TITLE
Speed up serialization and deserialization

### PR DESCRIPTION
**Pull request by andersfugmann**
Benchmarking against ocaml-protoc showed a huge number of allocations for both serialization and deserialization, which prompted some work on speeding up serialization and deserialization:
* A quick rewrite to use exceptions instead of the error monad showed a x2 speedup for deserialization
* Serializing directly to the output buffer yields yet another speed improvement for serialization (~x2 speedup)
* Deserialization reads directly from the input buffer to avoid allocations and makes good use of static evaluation. This improves deserialization speed by 2-4x, depending on input. Two strategies for parsing input: 
  * If input is ordered (its recommended to send fields in sorted order), construction is O(1).
  * If input is un-ordered a map is constructed with has O(n log n), and uses ref cells, which hurts the GC (adds roots)
* Improving code generation for extensions and constructors (make), which now uses default values for optional fields rather than using pattern matching to unpack values (potentially reduce GC strain and improve inlining opportunities)
Other changes includes:
  * A bug-fix for extensions, where setting an extension did not remove the previous values in some cases. 
  * Improve emitted code by stripping whitespace at end of line and ensure all files ends with an empty line

For simple structures, ocaml-protoc-plugin is still slower than `ocaml-protoc`, but for more complex structures speed is comparable. 

I'll note that `ocaml-protoc` has chosen to be non-compliant, and uses c stubs for faster encoding and decoding. Some observations on  `ocaml-protoc`:
  * Does not allow repeated enums
  * Sends fields in reverse order (which is allowed but not recommended)
  * Always sends fields, even when fields have default values 
  * Only support packed repeated fields 
  * No proto2 support
  * Does not support extensions

### CODE REVIEW

**Comment by andersfugmann** [comment]
Some benchmarks 

|  Name |  Old - ns/run |  New - ns/run| ratio |
|  -- |  -- |  -- | -- |
| string_list.M/Decode/Plugin | 311040.6960 | 131970.8184 | .42 |
| string_list.M/Decode/Protoc | 69894.1975 | 82798.6758 | 1.18 |
| string_list.M/Encode/Plugin | 233021.2744 | 116567.0649 | .50 |
| string_list.M/Encode/Protoc | 62315.6831 | 76078.9296 | 1.22 |
|  |
|  |
| float_list.M/Decode/Plugin | 76740.8830 | 34555.1781 | .45 |
| float_list.M/Decode/Protoc | 18662.5440 | 18538.2621 | .99 |
| float_list.M/Encode/Plugin | 42953.9669 | 44641.5460 | 1.03 |
| float_list.M/Encode/Protoc | 19822.1616 | 22271.0384 | 1.12 |
|  |
|  |
| int64_list.M/Decode/Plugin | 192442.6824 | 46931.4920 | .24 |
| int64_list.M/Decode/Protoc | 24973.4493 | 25913.0417 | 1.03 |
| int64_list.M/Encode/Plugin | 101449.5188 | 46641.8079 | .45 |
| int64_list.M/Encode/Protoc | 19726.9139 | 20643.0586 | 1.04 |
|  |
|  |
| enum.M/Decode/Plugin | 552.0980 | 274.8362 | .49 |
| enum.M/Decode/Protoc | 40.8793 | 40.1420 | .98 |
| enum.M/Encode/Plugin | 225.4306 | 174.6894 | .77 |
| enum.M/Encode/Protoc | 77.2908 | 71.7628 | .92 |
|  |
|  |
| string.M/Decode/Plugin | 645.4916 | 292.5425 | .45 |
| string.M/Decode/Protoc | 63.0482 | 70.7741 | 1.12 |
| string.M/Encode/Plugin | 286.8491 | 229.2601 | .79 |
| string.M/Encode/Protoc | 88.9577 | 87.3955 | .98 |
|  |
|  |
| float.M/Decode/Plugin | 491.4052 | 247.9175 | .50 |
| float.M/Decode/Protoc | 36.3592 | 40.4689 | 1.11 |
| float.M/Encode/Plugin | 174.0742 | 194.4858 | 1.11 |
| float.M/Encode/Protoc | 71.0880 | 70.6722 | .99 |
|  |
|  |
| int64.M/Decode/Plugin | 579.7528 | 259.3254 | .44 |
| int64.M/Decode/Protoc | 38.2384 | 40.8936 | 1.06 |
| int64.M/Encode/Plugin | 225.6232 | 190.2801 | .84 |
| int64.M/Encode/Protoc | 77.7386 | 71.9856 | .92 |
|  |
|  |
| bench.M/Decode/Plugin | 358543.7805 | 112197.4954 | .31 |
| bench.M/Decode/Protoc | 56696.3379 | 61007.7365 | 1.07 |
| bench.M/Encode/Plugin | 206013.8916 | 112104.4718 | .54 |
| bench.M/Encode/Protoc | 50472.0140 | 52438.8131 | 1.03 |

**Comment by andersfugmann** [comment]
I don't really know how the changes can be reviewed, as they are massive! I think the tests are pretty complete and tests a lot of things, as well as the benchmarks which also verifies results.

**Comment by andersfugmann** [comment]
@AndreasDahl Any suggestions on how we can get this PR merged? I understand that its huge, but I believe the test coverage quite high. 
A suggestion would be to focus on coding style and comment if the libraries needed for running the benchmark (`make bench`) should be added to the opam file.

**Comment by andersfugmann** [comment]
With the latest optimizations, ocaml-protoc-plugin is now on par (and in some cases actually faster) with protoc:

Numbers below shows relation to `protoc`. A value above one means that Ocaml-protoc-plugin is slower and below means faster. 
The benchmark is run with flambda settings: `-O3 -unbox-closures -remove-unused-arguments -rounds 3 -inline 100.00 -inline-max-depth 3 -inline-max-unroll 3`

| test | protoc | ocaml-protoc-plugin | ratio |
| -- | -- | -- | -- |
| string_list.M/Decode | 69097.7864 | 78123.2441 | 1.1306 |
| string_list.M/Encode | 73026.9203 | 57308.9066 | .7847 |
| float_list.M/Decode | 18099.2257 | 19993.6007 | 1.1046 |
| float_list.M/Encode | 20498.1777 | 11481.1299 | .5601 |
| int64_list.M/Decode | 21890.8594 | 17562.3905 | .8022 |
| int64_list.M/Encode | 18108.9827 | 12021.9094 | .6638 |
| enum.M/Decode | 58.6929 | 53.6873 | .9147 |
| enum.M/Encode | 103.6401 | 98.2260 | .9477 |
| string.M/Decode | 96.4106 | 91.4180 | .9482 |
| string.M/Encode | 115.0315 | 117.5707 | 1.0220 |
| float.M/Decode | 51.4995 | 51.6307 | 1.0025 |
| float.M/Encode | 113.2276 | 94.4504 | .8341 |
| int64.M/Decode | 63.4648 | 51.3960 | .8098 |
| int64.M/Encode | 92.6878 | 95.6652 | 1.0321 |
| bench.M/Decode | 51351.6396 | 49580.7279 | .9655 |
| bench.M/Encode | 52722.1153 | 33273.7429 | .6311 |

**Comment by andersfugmann** [comment]
With the latest optimizations, ocaml-protoc-plugin is now comparable with protoc:

Numbers below shows relation to `protoc`. A value above one means that Ocaml-protoc-plugin is slower and below means faster. 
The benchmark is run with flambda settings: `-O3 -unbox-closures -remove-unused-arguments -rounds 3 -inline 100.00 -inline-max-depth 3 -inline-max-unroll 3`

| name | protoc | plugin | ratio |
|  --  |   --   |   --   |  --   |
| string_list.M/Decode | 45673.3403 ns/run | 53547.6444 ns/run | 1.172 |
| string_list.M/Encode | 77058.1932 ns/run | 46928.1161 ns/run | .608 |
| float_list.M/Decode | 11195.2996 ns/run | 14448.8059 ns/run | 1.290 |
| float_list.M/Encode | 19415.1014 ns/run | 8767.3420 ns/run | .451 |
| int64_list.M/Decode | 16906.9672 ns/run | 14329.7493 ns/run | .847 |
| int64_list.M/Encode | 13556.7060 ns/run | 11329.0867 ns/run | .835 |
| enum.M/Decode | 31.9749 ns/run | 72.6818 ns/run | 2.273 |
| enum.M/Encode | 68.3581 ns/run | 59.7913 ns/run | .874 |
| string.M/Decode | 50.1519 ns/run | 91.4369 ns/run | 1.823 |
| string.M/Encode | 77.2197 ns/run | 86.7556 ns/run | 1.123 |
| float.M/Decode | 28.6674 ns/run | 72.1196 ns/run | 2.515 |
| float.M/Encode | 66.3969 ns/run | 62.3008 ns/run | .938 |
| int64.M/Decode | 30.8383 ns/run | 72.8756 ns/run | 2.363 |
| int64.M/Encode | 66.0895 ns/run | 58.9611 ns/run | .892 |
| bench.M/Decode | 157661.3070 ns/run | 151011.1603 ns/run | .957 |
| bench.M/Encode | 217168.8299 ns/run | 123210.2917 ns/run | .567 |
 

Benchmark still shows x2 slower decoding on simple messages (messages with only one field).

**Comment by andersfugmann** [comment]
@AndreasDahl Repinging on this again. I'll stop adding commits to this for now, and I'll look into some of the other issues. However, I'd like to get this merged soon, as I intend to base future work on top of this. Could I ask for a quick review? I don't know if you have some tests that you can run on top of this code (if its still being used actively), but I don't think an in-depth review is sensible at this point with all the changes made.

**Comment by andersfugmann** [comment]
@issuu/platypus @AndreasDahl do you have suggestions on how to proceed on this? 

I propose that we either.
1. We agree that as a general rule all code should be reviewed, and you will prioritizing reviewing.
2. We don't really care about having code on master reviewed. Remove the CODEOWERS and I will just push to master at will
3. Transfer the repository to me and you can create / maintain a local fork.

In case I don't get a timely response, I will start merging to main and prepare a new release, but its really not an ideal solution. I would much rather prefer 3. if Issuu has no interest in maintaining these repositories. I would propose the same for ocaml-zmq repository which also have a stale PR. ocaml-zmq repository should be transferred to the ocaml community though.

**Comment by andersfugmann** [comment]
Note that I really do not prefer solution 2 and think we should avoid if possible.

**Review by AndreasDahl — APPROVED** [review]
Apologies for the late review. I'll start the discussion internally on how we want to maintain this going forward.

**Pull request merged**
