### PR TITLE
Add extra fields to RPC endpoints

### PR DESCRIPTION
**Pull request by andersfugmann**
Add `service_name`, `method_name` and `package_name` to RPC modules. 

Closes #49

### CODE REVIEW

**Comment by andersfugmann** [comment]
@AndreasDahl / @tmcgilchrist Could I get a  review on the changes in this PR. The changes are relative small and strait forward. Apart from adding new fields to auto generated service structs, it slightly changes how the `name` field is constructed. I suggest reviewing all changes in one go (and not per commit).

**Review by cheng81 — APPROVED** [review]
Looks good to me 👍

**Review by AndreasDahl — APPROVED** [review]
Looks good to me. Thank you for the PR 👍

**Comment by andersfugmann** [comment]
Thanks both. Really appreciated.

**Comment by tmcgilchrist** [comment]
Looks good to me. Thanks.

**Pull request merged**
