### PR TITLE
Update bsconfig and package.json for 3.0.0

### PR DESCRIPTION
**Pull request by wokalski**
This PR updates the bucklescript-related files. Btw everything still works well in runtime 👍. Thanks for the maintenance of this repo. For the automated publish script we'd need an npm token of somebody. I used mine for the runtime so far but I can add someone to the repo. I also can add mine to the repo but it'd require giving me some access to the settings.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Is this still useful? It was last updated 3 years ago @andersfugmann @wokalski

**Comment by wokalski** [comment]
To be honest I was probably the only user of this at the time and I'm not one anymore. I'm not sure if we should support rescript at all.

**Comment by andersfugmann** [comment]
Should we close the issue then? And should we remove the package.json from this repository?

**Comment by wokalski** [comment]
I think so.

**Comment by andersfugmann** [comment]
Closing in favor of https://github.com/issuu/ocaml-protoc-plugin/pull/45

**Pull request closed without merging**
