### PR TITLE
Added dev dependencies to conf-protoc package

### PR DESCRIPTION
**Pull request by martinslota**
This adds dependencies to `conf-protoc` in order to ensure that Google's common `.proto` files get installed as well.

### CODE REVIEW

**Comment by andersfugmann** [comment]
Looks ok to me. But why is this needed?

**Comment by martinslota** [comment]
This is to support `.proto` files with Google imports.

Here's an example `test.proto`:

```proto
syntax = "proto3";

import "google/protobuf/timestamp.proto";

message M {
  google.protobuf.Timestamp field = 1;
}
```

This `Dockerfile` will work fine:

```Dockerfile
FROM ubuntu

RUN apt-get update && apt-get install -y protobuf-compiler libprotobuf-dev
COPY test.proto /
RUN echo "" | protoc --encode=M test.proto
```

If you drop `libprotobuf-dev`, it won't.

**Comment by martinslota** [comment]
If you don't want this, it's fine, I'll just make a separate `conf-protoc-dev` or `conf-protobuf-dev` package.

**Comment by wokalski** [comment]
@martinslota Even though I have the well known type proto files available and correctly picked up by `protoc`, actually using and generating code for them would have to be resovled, too.

**Comment by andersfugmann** [comment]
I forgot at the standard does mandate that these files are available, so I guess they should be present. 
I'll merge and publish

**Pull request merged**
