### PR TITLE
Support OCaml 4.06.x

### PR DESCRIPTION
**Pull request by wokalski**
As the first step towards BuckleScript support I added some small changes which make this plugin compatible with OCaml 4.06.

### CODE REVIEW

**Comment by andersfugmann** [comment]
Looks ok to me. 

One question before merge - what other steps are needed in order to compile with bucklescript? Would it make more sense to remove the `base` instead?

**Comment by wokalski** [comment]
@andersfugmann I removed `base` usage in the first iteration. Afterwards though, I decided to stub ("polyfill" if you will) the parts of `Base` which are used in the runtime. Practically it means adding a small `Base.ml` module along the main runtime. It contains a reimplementation of the tiny subset of Base required by `protobuf`. It was very little work, it has small size footprint, and it works fine for my needs.  Let me know what you think.

**Comment by andersfugmann** [comment]
Could you post the function in use which are not in stdlib?

**Comment by wokalski** [comment]
- `Map` module
- `Result` module
- `%` operator
- `Option` module
- `Int64` **operators**
- `Float.iround_down_exn`
- `String.to_list` (easy to replace with `List.init (String.length s) (String.get s)`)

And I think that's it. The rest exists inside `*Labels` modules.

**Comment by wokalski** [comment]
I can update this PR with the changes which make `protobuf` compile without `base`.

**Comment by andersfugmann** [comment]
I would welcome a PR to remove the need for base.
Please note that the code has changed alot, but I think its more or less stable for now.

The code currently makes use of ppx_let extension. I think it would be 
ok to change the code:

```ocaml
 let open Result.Let_syntax in
   let%bind v = f x in
   let%bind v = f x in
   ...
```

to: 
```ocaml
  let (>>=) v f = 
    match v with 
    | Ok v -> b v 
    | err -> err
 in 
 let return v = Ok v in
 
 f x >>= fun v -> 
 ...
 return v
```

The Map module would map trivially into stdlib.
`Float.iround_down_exn` would be `Float.to_int`
I don't remember what `%` operator is. If its modulo, it should just be coverted into `mod`.
For in64 and int32, we prob. need modules with exposes used operators as infix operators. 
The `String.to_list` is only used to dump data. It can trivially be converted into a loop using `String.get`.

I do perfer to use the labeled modules. I usually start by declaring used modules like:
```ocaml
module List = ListLables
```
at the top of each file, which uses list functions.

**Comment by andersfugmann** [comment]
And to make the code backward compatible, I would prefer using stdlib-shims, if that works with bucklescipt - rather than keep looking at the documentation to see if a function is available in 4.06.

**Comment by wokalski** [comment]
Great. I'll remove the dependency on base later today. I'll gladly remove ppx_let. Although I often use ppx's with BuckleScript, making public packages depend on them is painful because you somehow have to distribute compiled ppx binaries for all platforms. If you depend on users having the ppx somewhere it quickly becomes error prone.

**Comment by andersfugmann** [comment]
Hi. I just wanted to ping about the progress, as I am hoping to get this in before I make a new release.

**Comment by wokalski** [comment]
I'm sorry - different priorities took over my time. However, I've been doing it this morning and I'll finish soon.

**Comment by andersfugmann** [comment]
Awesome. Thanks a lot.

**Pull request merged**
