### PR TITLE
Make proto3 optional fields into option types

### PR DESCRIPTION
**Pull request by andersfugmann**
This change changes proto3 optional fields to be option types instead of an polymorphic variant. 
Currently proto3 optional fields are mapped as a `oneof _<field_name> { <field_type> <field_name> = 1}`. This maps to a 
polymorphic variant:

```
type t = { _<field_name>: [ `not_set | `<field_name> of <field_type> ]; ... }
```

The change proposed is to make optional fields in the same way as proto2:
```
type t = { <field_name>: <field_type> option; ... } 
```

### CODE REVIEW

**Comment by andersfugmann** [comment]
Apparently the github ubuntu runners does not have a sufficiently recent version of protoc (>= 3.12 required). Ill look into that later.

**Review by AndreasDahl — APPROVED** [review]
Thanks a lot for this contribution @andersfugmann. I haven't yet properly familiarized myself with this repo, so this change would have taken me considerable effort.

When we get this change into the master branch, will you be able and willing to submit a release to opam-repository for us? Otherwise i will do so next week.

**Comment by andersfugmann** [comment]
Thanks for reviewing. I will merge once the tests are green.

**Comment by andersfugmann** [comment]
I can create a new release over the weekend. I see you already tagged a v4.3. Should I override this tag, or create a new release tag?

**Comment by AndreasDahl** [comment]
Feel free to overwrite the 4.3.0 tag. I was intending to release it as-is, but I think we should rather have your changes in first. This was my release PR https://github.com/ocaml/opam-repository/pull/22085

**Comment by andersfugmann** [comment]
https://github.com/ocaml/opam-repository/pull/22090

**Pull request merged**
